### ISSUE TITLE
make units table sortable by column

### ISSUE THREAD

**Issue by magland** [laboratorybox/labbox-ephys#118]
User clicks any column to sort ascending, descending

Note: it is important to sort numeric columns appropriately

Advanced (lower priority): Allow sorting by multiple columns - clicking on column A followed by column B should sort primary by B and then secondary by A.

![image](https://user-images.githubusercontent.com/3679296/100902248-b5820a00-3492-11eb-971e-ed03928bb2c3.png)

**Comment by jsoules** [comment]
Resolved in PR #132 .
