### ISSUE TITLE
UnitsTable: make all columns sortable

### ISSUE THREAD

**Issue by magland** [laboratorybox/labbox-ephys#135]
In my opinion, this should be done by having a layer between the metrics and the table itself

[Special columns ---- External metrics ---- Computed metrics]
-> [Some layer that handles all different types of columns in one interface]
-> [The actual table]

In this way, all columns are sortable -- and in fact the first column does not need to be treated as a special column (for resetting the sorting)

**Comment by jsoules** [comment]
I think you fixed this, no?

**Comment by magland** [comment]
yes, closing.
