### ISSUE TITLE
Add unison, etc. to the devcontainer Docker image

### ISSUE THREAD

**Issue by magland** [laboratorybox/labbox-ephys#147]
In order to use the code sync task unison and unison-fsmonitor must be installed
apt install unison and the following gets the binary of unison-fsmonitor:

curl -L -o unison-fsmonitor https://github.com/TentativeConvert/Syndicator/raw/master/unison-binaries/unison-fsmonitor

**Comment by magland** [comment]
Worth noting in the readme.txt: git does not redundantly store identical files.

Also describe the vscode task that uses unison

**Comment by magland** [comment]
In that last comment, I am referring to a readme.txt that should exist in src/extensions/readme.txt to explain what's happening with the code sync.

**Comment by magland** [comment]
The unison-fsmonitor will need to be placed somewhere in the PATH. Does it belong in /usr/bin? not sure.

**Comment by jsoules** [comment]
Added update to docker container; I put it in /usr/local/bin. Hey, it's our container, right?

**Comment by magland** [comment]
Great! I'm closing this issue.
