### ISSUE TITLE
readme.txt to explain code sync

### ISSUE THREAD

**Issue by magland** [laboratorybox/labbox-ephys#148]
We need a readme.txt in the src/extensions/ folder that explains what's going on wrt bi-directional code syncing between src/extensions and jupyterlab/......src/extensions.

It will also be nice to explain why it is done this way. Basically, it is difficult to share .ts code between two different yarn packages that have different build requirements.

**Comment by magland** [comment]
This is still needed, but of course it's no longer bi-direction. And we need some description of what's going on in the README or developer documentation somewhere.

**Comment by magland** [comment]
Oops, actually it is bi-directional.

**Comment by jsoules** [comment]
Resolved by PR #209.
