### ISSUE TITLE
timeseries view: require click prior to mouse wheel scrolling

### ISSUE THREAD

**Issue by magland** [laboratorybox/labbox-ephys#159]
When scrolling through a jupyter notebook or scrolling down a web page you don't want the scrolling to suddenly stop when it hovers over a timeview widget as the zoom functionality kicks in. I suggest we require that the widget is clicked on first before the zoom functionality kicks in

**Comment by jsoules** [comment]
Okay, I have an idea of how to do this. I'll work on this issue next.
