### ISSUE TITLE
Elec geom view: set max value for pixelRadius

### ISSUE THREAD

**Issue by magland** [laboratorybox/labbox-ephys#199]
Sometimes the electrode markers are really too big, like when the number of channels is small (e.g., a tetrode).
Let's detect if the pixel radius is greater than, say, 12, we should scale the entire geometry down so that the size is more reasonable.

**Comment by magland** [comment]
Here's what we want to avoid:

![image](https://user-images.githubusercontent.com/3679296/102401441-51daff00-3fb1-11eb-8171-3c311f53b1db.png)

**Comment by magland** [comment]
there are a bunch of elec geom widgets floating around. You should modify the one in extensions/electrodegeometry

**Comment by jsoules** [comment]
Resolved by PR #205.
