### ISSUE TITLE
avg waveform keypress up/down scale amp

### ISSUE THREAD

**Issue by magland** [laboratorybox/labbox-ephys#268]

**Comment by magland** [comment]
Need to scale the amp scale factor on up/down button click or up/down arrow key press.

* Create a left panel on the average waveforms view...
* Register some actions (Up scale and down scale) - similar to what is done in the TimeWidget.

Here's how this works for the Time Widget:

The custom actions of the Time Widget are sent to the mainLayer (canvas widget layer) and then we have the following handleKeyboardEvent:

```typescript
export const handleKeyboardEvent: KeyboardEventHandler = (e: KeyboardEvent, layer: CanvasWidgetLayer<TimeWidgetLayerProps, LayerState>): boolean => {
    const props = layer.getProps()
    if (!props) return true
    for (let a of props.customActions || []) {
        if (a.type === 'button') {
            if (a.keyCode === e.keyCode) {
                a.callback()
                return false
            }
        }
    }
    ...
}
```

Ultimately those actions trigger the following callbacks in TimeseriesWidgetNew.tsx

```typescript
const [actions, setActions] = useState<TimeWidgetAction[] | null>(null)
    const _handleScaleAmplitudeUp = useCallback(() => {
        recordingSelectionDispatch({type: 'ScaleAmpScaleFactor', multiplier: 1.15})
    }, [recordingSelectionDispatch])
    const _handleScaleAmplitudeDown = useCallback(() => {
        recordingSelectionDispatch({type: 'ScaleAmpScaleFactor', multiplier: 1 / 1.15})
    }, [recordingSelectionDispatch])
```

An example of creating the left panel is in SpikeAmplitudesView.tsx:

```
const SpikeAmplitudesView: FunctionComponent<SortingViewProps> = ({recording, sorting, selection, selectionDispatch, width, height}) => {
    return (
        <Splitter
            width={width || 600}
            height={height || 900} // how to determine default height?
            initialPosition={200}
        >
            <SelectUnitsWidget sorting={sorting} selection={selection} selectionDispatch={selectionDispatch} />
            <SpikeAmplitudesTimeWidget
                recording={recording}
                sorting={sorting}
                unitIds={selection.selectedUnitIds || []}
                {...{width: 0, height: 0}} // filled in by splitter
                selection={selection}
                selectionDispatch={selectionDispatch}
            />
        </Splitter>
    )
}
```

See TimeWidgetToolbarNew.tsx for example of toolbar (that holds the actions)

**Comment by jsoules** [comment]
I've been working this up and it's nearly there, but I wanted to clarify some functionality.

Is it intended that the amplitude for each unit be modifiable individually? I feel like we discussed this but I don't remember what the answer was.

If no, all units' waveforms should be scaled together:
This is what I have built out. However, the snag is the `TimeSeriesWidget` model operates on a `RecordingSelectionDispatch`. Amplitude-scaling is not a currently implemented feature for reducers that touch on sortings only. However, `AverageWaveformsView` is a sorting-view plugin, and doesn't have a `RecordingSelectionDispatch`. What would be the right way for it to get one?

If yes, each unit's waveforms should be amplitude-scaled individually:
On reflection, if we want to do this, there's no reason to set the amplitude scaling factor as shared state: it would probably do better to live on the individual `AverageWaveformView2` components. That actually simplifies things, but I'll need to back out a few changes before wrapping it up.

**Comment by magland** [comment]
They should all scale together, and use the same global scale factor as the timeseries

**Comment by jsoules** [comment]
Gotcha. In that case we’ll need to figure an appropriate way to give a sorting view plugin access to the recording properties, right? Let’s chat about that Tuesday?

**Comment by magland** [comment]
> In that case we’ll need to figure an appropriate way to give a sorting view plugin access to the recording properties, right?

The SortingSelection actions include all RecordingSelection actions, so you can use SortingSelectionDispatch to dispatch all recording selection actions.
