### ISSUE TITLE
Splitter and VSplitter: Rename gripWidth to gripThickness

### ISSUE THREAD

**Issue by magland** [laboratorybox/labbox-ephys#289]
I thought about calling in height, but it's width of the grip line... so it's not width in the meaning of horizontal width... it's like pen width. Really thickness is the word. It should be called thickness.

_Originally posted by @magland in https://github.com/laboratorybox/labbox-ephys/pull/262#discussion_r551539890_

**Comment by jsoules** [comment]
Resolved in PR #300.
