### ISSUE TITLE
useHitherJob.ts: improve code flow with switch statement

### ISSUE THREAD

**Issue by magland** [laboratorybox/labbox-ephys#296]
There's a return at the end of the previous conditional (l. 51), so it might be clearer if this starts a new conditional statement entirely rather than immediately jumping to else-if. This would also let you use a single line to throw the error when `state.job` is undefined, rather than having to repeat it in each branch.

I'd probably also lean toward a switch statement on `state.status`.

_Originally posted by @jsoules in https://github.com/laboratorybox/labbox-ephys/pull/278#discussion_r552234600_

**Comment by jsoules** [comment]
Resolved in PR #299
