### ISSUE TITLE
update packages for security fixes

### ISSUE THREAD

**Issue by jsoules** [laboratorybox/labbox-ephys#298]
`$ yarn audit` indicates 3 packages with high-severity security vulnerabilities, all dependencies of `react-scripts`.

Looks like that version is pegged to `3.4.1` (`package.json` has "3.4.1" rather than "^3.4.1" or ">=3.4.1"). If there's not a specific compatibility issue, we should allow a more recent version so that the vulnerabilities in the dependencies can be fixed.

**Comment by jsoules** [comment]
Happy to take care of this, it should be a trivial fix--just wanted to check first that we don't have a reason we're using that particular version.

**Comment by magland** [comment]
Sure, go ahead and update. thx

**Comment by jsoules** [comment]
Resolved in PR #305.
