### ISSUE TITLE
Revise labbox-ephys installation instructions for Mac

### ISSUE THREAD

**Issue by jsoules** [laboratorybox/labbox-ephys#35]
Snags I hit:

 - It's in there already, but users should definitely confirm that `docker run hello-world` actually works from CLI before proceeding
 - home directory structure in the instructions assumes ubuntu/linux-style with user directory in /home/$USER but on my mac this was /USERS/$user
 - Might be a good idea to specify the version of Python to install via conda; a full exposition is beyond the scope etc etc but they should at least know to target 3.7 and install numpy.
 - Command lines in the "Launch the container" example box use the $LABBOX_EPHYS_DATA_DIR envvar, but we set it as $LABBOX_EPHYS_DATA above.

That said, having completed the instructions, I can connect to a basic labbox-ephys UI on localhost:15310. I see that the instructions for setting up a local compute resource are marked as obsolete so I haven't dug into those.

**Comment by magland** [comment]
Thanks. I'll update the docs.
Could you also try to import one of the spikeforest examples? And see if you can view the timeseries for the imported recording?

**Comment by jsoules** [comment]
Both of these things also work--it looks like we're good!

The exact steps for importing are a little confusing--the "Download" button is replaced entirely by the "Import" button, so it isn't immediately obvious that you need another click before the recording is fully imported. At some point, we might consider keeping both buttons visible, and greying out the "download" one (possibly replacing the text like 'Already Downloaded') for recordings which already exist in the local kachery store. But that's not part of this ticket.

**Comment by magland** [comment]
Agree.
