### ISSUE TITLE
Problem hosting compute resource

### ISSUE THREAD

**Issue by magland** [laboratorybox/labbox-ephys#37]
Reported by Fan: 
```
hither-compute-resource start-kachery-server
Unexpected command: start-kachery-server
```

Oops I need to get the latest hither deployed to pypi... I'll follow up...

**Comment by magland** [comment]
Please do the following for now:
```
pip install hither==0.2.0a2
```

**Comment by wufan0504** [comment]
Somehow now the site-packages doesn't see numpy?

Successfully installed hither-0.2.0a2
(labbox) wufan@DBC-Linux:~/labbox/compute_resource$ hither-compute-resource config
Traceback (most recent call last):
  File "/home/wufan/anaconda3/envs/labbox/bin/hither-compute-resource", line 3, in <module>
    from hither import computeresource, __version__
  File "/home/wufan/anaconda3/envs/labbox/lib/python3.8/site-packages/hither/__init__.py", line 3, in <module>
    from .core import function, container, additional_files, local_modules, opts
  File "/home/wufan/anaconda3/envs/labbox/lib/python3.8/site-packages/hither/core.py", line 9, in <module>
    from .job import Job
  File "/home/wufan/anaconda3/envs/labbox/lib/python3.8/site-packages/hither/job.py", line 5, in <module>
    import kachery as ka
  File "/home/wufan/anaconda3/envs/labbox/lib/python3.8/site-packages/kachery/__init__.py", line 1, in <module>
    from .core import set_config, get_config, config
  File "/home/wufan/anaconda3/envs/labbox/lib/python3.8/site-packages/kachery/core.py", line 2, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

**Comment by magland** [comment]
pip install numpy?

**Comment by wufan0504** [comment]
But I should have numpy already? use it all the time.. I'm a little hesitant to install these separately in different environment, or should I be?

**Comment by magland** [comment]
Are you in a conda environment? Maybe that environment does not have numpy. You can check, for example,

python -c "import numpy; print(numpy.__version__)"

**Comment by wufan0504** [comment]
Yes, I have been using the conda environment for the past 5 or so updates and have had no issue until just now

**Comment by wufan0504** [comment]
Does it look like a recent change from python3.7 to python3.8 may have caused this?


(base) wufan@DBC-Linux:~$ python -c "import numpy; print(numpy.version)"
<module 'numpy.version' from '/home/wufan/anaconda3/lib/python3.7/site-packages/numpy/version.py'>

(labbox) wufan@DBC-Linux:~$ python -c "import numpy; print(numpy.version)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'

  File "/home/wufan/anaconda3/envs/labbox/lib/python3.8/site-packages/kachery/core.py", line 2, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

**Comment by magland** [comment]
It looks like you ran that command from 2 different conda environments. One environment has numpy, the other does not.

Conda environments are meant to be disposable, you could just create a new one and start over.

I'd definitely recommend 'pip install numpy' from the (labbox) environment. That module is not in that environment.

**Comment by wufan0504** [comment]
Yes, I intentionally got out of the labbox conda environment and checked numpy and it was there. While inside labbox conda environment, it's not. 

It just confuses me that I've hosted the servers multiple times in the labbox conda environment in the past and it's always fine until I installed the most recent hither.

**Comment by wufan0504** [comment]
I just installed numpy in the labbox conda environment, and the "config" command ran ok. But now another thing seems missing when trying to run kachery-server:

(labbox) wufan@DBC-Linux:~/labbox/compute_resource$ hither-compute-resource start-kachery-server
RUNNING SHELL SCRIPT: /tmp/tmp_shellscript_8shaw_pq/script.sh
++ id -u
+ USER_ID=1000
++ id -g
+ GROUP_ID=1000
+ USER_INSIDE_CONTAINER=labbox
+ BASE_IMAGE=magland/kachery-server:0.1.1
+ NEW_IMAGE=magland/kachery-server-nonroot:0.1.1
+ INJECT_USER_DIR=/home/wufan/anaconda3/envs/labbox/lib/python3.8/site-packages/hither/docker_inject_user
+ docker build -f /home/wufan/anaconda3/envs/labbox/lib/python3.8/site-packages/hither/docker_inject_user/injectUser.Dockerfile -t magland/kachery-server-nonroot:0.1.1 --build-arg BASE_IMAGE=magland/kachery-server:0.1.1 --build-arg NEW_USER=labbox --build-arg NEW_UID=1000 --build-arg NEW_GID=1000 /home/wufan/anaconda3/envs/labbox/lib/python3.8/site-packages/hither/docker_inject_user
unable to prepare context: path "/home/wufan/anaconda3/envs/labbox/lib/python3.8/site-packages/hither/docker_inject_user" not found

**Comment by magland** [comment]
okay thanks! I know what's happening there will fix shortly...

**Comment by magland** [comment]
Referencing https://github.com/flatironinstitute/hither/pull/132
This will be fixed soon.

**Comment by magland** [comment]
Please try again with:
pip install hither==0.2.0a3

**Comment by wufan0504** [comment]
Ok, now I don't have any missing package issue. Running into problem starting the event-stream-server

Successfully built 6b88f1c79c04
Successfully tagged magland/eventstreamserver-nonroot:0.1.1
+ exec docker run -p 15402:8080 -v /home/wufan/labbox/compute_resource/event-stream-server:/event-stream-server -it magland/eventstreamserver-nonroot:0.1.1
docker: Error response from daemon: driver failed programming external connectivity on endpoint keen_brahmagupta (010dd546acacd205ad69044a0ee6d2d9ffcc8e2538220866036bcd9331d471bd): Bind for 0.0.0.0:15402 failed: port is already allocated.
ERRO[0002] error waiting for container: context canceled

**Comment by magland** [comment]
That port seems to already be allocated. An old container is probably still running. Try killing all your running docker containers.

**Comment by wufan0504** [comment]
Great, after stopping all docker containers, the compute resource started fine. 
Then I tried to run Mountainsort on a locally imported dataset, and it errored immediately. The error does not show up on the browser, but on terminal it says:

> 
> Starting compute resource: DBC-Linux
>                                     Responding with error: 500 incorrect or missing signature
> Responding with error: 500 incorrect or missing signature

**Comment by magland** [comment]
Okay, we'll look into that.

**Comment by wufan0504** [comment]
Just tried alpha .5, stuck at sorting again. Now the terminal shows this error. Seems to be related to event stream. How do I know if I had configured this correctly?

[2020-06-17 09:38:55,529] ERROR in app: Exception on /api/create_hither_job [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/labbox-ephys/python/api/api.py", line 84, in create_hither_job
    hither_config['job_handler'] = _create_job_handler_from_config(job_handler_config)
  File "/labbox-ephys/python/api/api.py", line 56, in _create_job_handler_from_config
    jh = hi.RemoteJobHandler(event_stream_client=esc, compute_resource_id=compute_resource_id)
  File "/usr/local/lib/python3.6/dist-packages/hither/remotejobhandler.py", line 43, in __init__
    stream.write_event(dict(type=ComputeResourceActionTypes.ADD_JOB_HANDLER, handler_id=self._handler_id))
  File "/usr/local/lib/python3.6/dist-packages/hither/eventstreamclient.py", line 67, in write_event
    self.write_events([event])
  File "/usr/local/lib/python3.6/dist-packages/hither/eventstreamclient.py", line 79, in write_events
    assert result.get('success', False), 'Error writing to event stream.'
AssertionError: Error writing to event stream.

**Comment by wufan0504** [comment]
Actually I found that the source of error for my previous two posts as incorrect password for event stream. This was not obvious but I managed to get it right this time. Now the spike sorting job is starting, but then I got this error: missing module 'pynwb'

Waiting for remote compute resource to respond...
======== Created hither job: PnHrGeDpzxVmQIU mountainsort4

Handling job: mountainsort4
Uploading to kachery --- (905.4 MiB): /data/kachery-storage/sha1/58/63/07/5863072e3fdef93186f8b977b7f3021c9b29cb48 -> http://localhost:15401/set/sha1/5863072e3fdef93186f8b977b7f3021c9b29cb48?channel=readwrite&signature=3784dbf1cdd52304a8448673bf9add6582729fb5
File uploaded (905.4 MiB) in 4.947313070297241 sec
Uploading to kachery --- (560.4 KiB): /data/kachery-storage/tmp/tmpm42akd80/text.txt -> http://localhost:15401/set/sha1/ee515d914d0cf02af25cfb2b7a515ab1bbeef45e?channel=readwrite&signature=a85de94c7a85ad56063e347b47965654f95959b7
File uploaded (560.4 KiB) in 0.01799178123474121 sec
Traceback (most recent call last):
  File "/labbox-ephys/python/api/api.py", line 115, in hither_job_wait
    job.wait(0)
  File "/usr/local/lib/python3.6/dist-packages/hither/job.py", line 103, in wait
    raise self._exception
Exception: No module named 'pynwb'

**Comment by magland** [comment]
Thanks for these reports. We will get around to fixing the spike sorting. Let's follow up next week about it.
