### ISSUE TITLE
elec geom not displaying for certain recordings

### ISSUE THREAD

**Issue by magland** [laboratorybox/labbox-ephys#64]
Elec geom not visible for:

http://ephys1.laboratorybox.org/default/recording/cortexlab-drift-dataset1?feed=sha1://5f1dad33f30081ce1206c10c668cd31936179733/feed.json

whereas it is visible for others:

http://ephys1.laboratorybox.org/default/recording/allen_mouse419112_probeE?feed=sha1://5f1dad33f30081ce1206c10c668cd31936179733/feed.json

I confirmed that the geom information is being sent to the client (by looking at incoming messages on the console). So this has something to do with the elec geom widget rendering.

**Comment by jsoules** [comment]
The 'not displaying' example is now displaying correctly--something in our recent rewrites must've fixed it. Closing as no longer a problem.
